### ISSUE TITLE
create tags for pre/alpha/beta releases

### ISSUE THREAD

**Issue by hasufell** [SimonN/Lix#4]
git tags make it easy to create releases on which distributors can rely on since creating a tarball from master is unreliable as well as directly pulling from git

**Comment by AMDmi3** [comment]
+1 to this as well. There are commits that set version, however there are no tags.

**Comment by SimonN** [comment]
I will do tagging from now on. My version labelling is weird; only a date, no further semantics. I will use vYYYY-MM-DD.

Nonetheless, branch master should always be reliable in this project.

**Comment by hasufell** [comment]
> Nonetheless, branch master should always be reliable in this project.

we can't package from master, so it's more important that the releases are reliable

**Comment by SimonN** [comment]
Yeah, I understand how packaging mechanisms/guidelines, or simply best practices, forbid dynamically pulling the master head.
